# Generated by Django 3.1.7 on 2021-02-26 20:14

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('frozen', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('personal_amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=1024)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1024)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('fifth_ribbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fifth', to='core.ribbon')),
                ('first_ribbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first', to='core.ribbon')),
                ('fourth_ribbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fourth', to='core.ribbon')),
                ('second_ribbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second', to='core.ribbon')),
                ('third_ribbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third', to='core.ribbon')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
        ),
    ]
