# Generated by Django 3.1.7 on 2021-02-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210222_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='fifth_ribbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fifth', to='core.ribbon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_ribbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first', to='core.ribbon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fourth_ribbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fourth', to='core.ribbon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='second_ribbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second', to='core.ribbon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='third_ribbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third', to='core.ribbon'),
        ),
    ]
