# Generated by Django 3.1.7 on 2021-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210314_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
