# Generated by Django 3.1.7 on 2021-03-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210314_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='personal_amount',
        ),
    ]
