# Generated by Django 3.1.7 on 2021-03-25 21:52

import core.models.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_transaction_personal_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32, unique=True, validators=[core.models.model.validate32])),
                ('note', models.CharField(blank=True, help_text='Note where this secret is being used', max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default='default', max_length=1024, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
